version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: twilio-ruby
    versions:
    - 5.46.1
    - 5.47.0
    - 5.48.0
    - 5.49.0
    - 5.50.0
    - 5.51.0
    - 5.52.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
    - 1.11.3
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: tzinfo
    versions:
    - 1.2.9
  - dependency-name: paper_trail
    versions:
    - 11.1.0
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: mini_magick
    versions:
    - 4.9.4
  - dependency-name: devise
    versions:
    - 4.7.1
